Vagrant.configure("2") do |config|

	config.vm.define "allserver" do |node|
  	node.vm.box = "centos/7"
  	node.ssh.insert_key = false
  	node.vm.hostname = "allserver"
	  node.vm.network :private_network, ip:"192.168.0.1"
  end

	config.vm.provider :virtualbox do |vb|
    vb.name = "test1"
  end

	config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
		ansible.playbook = "./ansible/allserver.yml"
		ansible.groups = {
      "group1" => ["allserver"]
    }
  end
end
