version: '3'
services:
  web:
    image: nginx:alpine
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
      - ./helloworld/public:/var/www/laravel/public
    ports:
      - 80:80
    links:
      - phpfpm
  phpfpm:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./helloworld/:/var/www/laravel/
    links:
      - db
    env_file: .env
  db:
    image: mysql:5.7.23
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
volumes:
  mysql-data:
    driver: 'local'
